### PR TITLE
refactor: use aegir

### PR DESCRIPTION
**Pull request by dignifiedquire**
@diasdavid can't get the gulp file to do the correct setup, could you take a look please?

### CODE REVIEW

**Comment by daviddias** [comment]
Why create a gulp file for extra setup? The test is quite small and only runs in Node.js

**Comment by dignifiedquire** [comment]
To have it run in the browser as well, or is this intended only for node usage?

**Comment by daviddias** [comment]
The browser checks were not made yet. Let's not urge that, the code might need refactoring anyway.

**Comment by dignifiedquire** [comment]
okay will move things to node only

**Comment by dignifiedquire** [comment]
@diasdavid done

**Comment by daviddias** [comment]
woooo :D

**Pull request merged**
